# -*- coding: utf-8 -*-
"""Trabajo Final Text Mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgSz5VcM9bNekDQt1mkVi1pwBtEevzNc

###Librerias
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import seaborn as sns

"""###Petición a la web"""

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
response = requests.get('https://www.transfermarkt.es/espana/startseite/verein/3375', headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')

"""### Scraping y creacion Data Frame con Pandas"""

tabla = soup.find(class_='responsive-table')
filas = tabla.find('tbody').find_all('tr')

lista_jugadores = []

for fila in filas:
    tds = fila.find_all('td', recursive=False)
    if len(tds) < 5:
        continue

    posicion = tds[0].get('title')
    if not posicion:
        continue

    td_hauptlink = tds[1].find('td', class_='hauptlink')
    nombre_tag = td_hauptlink.find('a') if td_hauptlink else None
    nombre = nombre_tag.get_text().strip()

    edad = tds[2].get_text().strip()

    club_tag = tds[3].find('a')
    club = club_tag['title']

    valor_tag = tds[4].find('a')
    valor = valor_tag.get_text().strip()

    jugador = {
        'Nombre': nombre,
        'Posicion': posicion,
        'Edad': edad,
        'Club': club,
        'Valor': valor
    }

    lista_jugadores.append(jugador)

df = pd.DataFrame(lista_jugadores)

#Limpiar los datos para poder usar los valores numéricos de edad y valor
df['Edad'] = df['Edad'].str.split('(').str[1].str.replace(')', '').astype(int)

df['Valor'] = df['Valor'].str.replace(' €', '').str.replace(',', '.')

df['Valor'] = df['Valor'].apply(lambda x: float(x.replace(' mill.', ''))) #Elimina el texto " mill." y convierte la cifra a número decimal (float)
##lambda: función rápida de una sola línea que transforma cada celda (x)

df

"""## Análisis

### Análisis por posiciones
"""

print('--- Jugadores por Posición  ---')

#Orden de las posiciones
orden_posiciones = ['Portero', 'Defensa', 'Centrocampista', 'Delantero']

# Convertir la columna 'Posicion' a un tipo categórico con el orden especificado
df['Posicion'] = pd.Categorical(df['Posicion'], categories=orden_posiciones, ordered=True)

#Agrupar por posiciones
jugadores_por_posicion_ordenado = df.sort_values(by='Posicion').groupby('Posicion', observed = False)

for posicion, grupo in jugadores_por_posicion_ordenado:
    valor_total_posicion = grupo['Valor'].sum()
    valor_medio_posicion = grupo['Valor'].mean()
    print(f'\nPosición: {posicion} (Valor Total: {valor_total_posicion:.2f} M€ | Valor Medio: {round(valor_medio_posicion, 2)}M€)')
    for index, jugador in grupo.iterrows():
        print(f"  - {jugador['Nombre']} (Club: {jugador['Club']}, Edad: {jugador['Edad']}, Valor: {jugador['Valor']}M€)")

#Contar por posicion
cposiciones = df['Posicion'].value_counts()

# 2. Configurar el tamaño y estilo del gráfico
plt.figure(figsize=(8, 5))

# 3. Crear el gráfico de barras (asignando colores distintos a cada barra)
barras = cposiciones.plot(
    kind='bar',
    color = ['#4C72B0', '#DD8452', '#55A868', "#B53539"]
)
plt.title('Distribución Táctica de la Selección Española', fontsize=14, fontweight='bold')
plt.xlabel('Posición', fontsize=12)
plt.ylabel('Número de Jugadores', fontsize=12)

plt.xticks(rotation=0)

for i, valor in enumerate(cposiciones):
    plt.text(i, valor + 0.15, str(valor), ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

"""### Análisis por Valor de Mercado"""

#Valor medio
media_valor = df['Valor'].mean()
print(f"Valor medio de la plantilla: {media_valor:.2f} millones de €\n")

#Ordenar los jugadores por valor
df_ordenado = df.sort_values(by='Valor', ascending=False)
print(df_ordenado[['Nombre', 'Posicion', 'Valor']])

#Top 5 valor
print("--- TOP 5 JUGADORES MÁS VALIOSOS ---")
print(df_ordenado[['Nombre', 'Posicion', 'Valor']].head(5))

print("\n")

#Menos valiosos
print("--- 5 JUGADORES CON MENOR VALOR ---")
print(df_ordenado[['Nombre', 'Posicion', 'Valor']].tail(5))

plt.figure(figsize=(10, 6))
sns.histplot(df['Valor'], bins=10, kde=True, color='skyblue', edgecolor='black')
plt.title('Distribución de los Valores de Mercado de los Jugadores', fontsize=14, fontweight='bold')
plt.xlabel('Valor de Mercado (M€)', fontsize=12)
plt.ylabel('Frecuencia', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
plt.scatter(df['Edad'], df['Valor'], alpha=0.7, color='skyblue')

#Añadir etiquetas de texto para cada jugador
for i, row in df.iterrows():
    plt.text(row['Edad'] + 0.5, row['Valor'], row['Nombre'], fontsize=9, ha='left', va='center')

plt.title('Relación entre Edad y Valor de Mercado de los Jugadores', fontsize=14, fontweight='bold')
plt.xlabel('Edad', fontsize=12)
plt.ylabel('Valor de Mercado (M€)', fontsize=12)
plt.grid(True, linestyle='-', alpha=0.6)
plt.tight_layout()
plt.show()

#Preprar los datos
valor_por_club = df.groupby('Club')['Valor'].sum().sort_values(ascending=False)
valor_total = df['Valor'].sum()

#Gráfico
plt.figure(figsize=(10, 8))

wedges, texts, autotexts = plt.pie(
    valor_por_club,
    labels=valor_por_club.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=plt.cm.tab20.colors,#colores
    wedgeprops={'edgecolor': 'black', 'width': 0.4}
)
#Titulo
plt.text(0, 0, f'Valor Total\n{valor_total:.1f} mill. €',
         ha='center', va='center', fontsize=12, fontweight='bold')
plt.title('Peso Económico: Valor de Mercado Aportado por Club', fontsize=15, fontweight='bold')
plt.axis('equal')
plt.tight_layout()
plt.show()

"""### Mapas de Calor"""

#Preparar los datos para el mapa de calor
valor_por_posicion_club = df.groupby(['Posicion', 'Club'], observed=False)['Valor'].sum().unstack(fill_value=0)

#Crear el mapa de color
plt.figure(figsize=(14, 8))
sns.heatmap(valor_por_posicion_club, annot=True, fmt=".1f", cmap="viridis", linewidths=.5, cbar_kws={'label': 'Valor de Mercado (M€)'})
plt.title('Concentración de Valor de Mercado por Posición y Club', fontsize=16, fontweight='bold')
plt.xlabel('Club', fontsize=12)
plt.ylabel('Posición', fontsize=12)
plt.xticks(rotation=45)
plt.setp(plt.gca().get_xticklabels(), ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""###Gráfico de Pesos"""

#Prepara los datos
conteo_clubes = df['Club'].value_counts()
max_jugadores = conteo_clubes.max()

#Preparar el gráfico
G = nx.Graph()
centro = 'España'
G.add_node(centro, tipo='Centro')

#Diccionario para guardar las coordenadas X, Y exactas de cada elemento
posiciones = {centro: np.array([0.0, 0.0])} # España en el centro exacto

#Distincia y la 'orbita' con el centro
num_clubes = len(conteo_clubes)
angulos = np.linspace(0, 2 * np.pi, num_clubes, endpoint=False)

for i, (club, cantidad) in enumerate(conteo_clubes.items()):
    G.add_node(club, tipo='Club', jugadores=cantidad)
    G.add_edge(centro, club, weight=cantidad)
    radio = 1 + (max_jugadores - cantidad) * 0.8

    x = radio * np.cos(angulos[i])
    y = radio * np.sin(angulos[i])
    posiciones[club] = np.array([x, y])

plt.figure(figsize=(12, 10))

#Sacar los nodos
nodos_centro = [n for n, attr in G.nodes(data=True) if attr.get('tipo') == 'Centro']
nodos_club = [n for n, attr in G.nodes(data=True) if attr.get('tipo') == 'Club']

#Hacer que el tamaño de la burbuja del club también crezca según sus jugadores
tamaños_club = [G.nodes[n]['jugadores'] * 800 for n in nodos_club]

#Dibujar las líneas de conexión (más gruesas = más jugadores)
pesos_aristas = [G[u][v]['weight'] for u, v in G.edges()]
nx.draw_networkx_edges(G, posiciones, width=pesos_aristas, alpha=0.4, edge_color='gray')

#Nodos
nx.draw_networkx_nodes(G, posiciones, nodelist=nodos_centro, node_color='#C44E52', node_size=4000, edgecolors='black')
nx.draw_networkx_nodes(G, posiciones, nodelist=nodos_club, node_color='#4C72B0', node_size=tamaños_club, edgecolors='black')

#Textos
nx.draw_networkx_labels(G, posiciones, font_size=10, font_weight='bold')

plt.title('Mapa de Influencia: Peso de los Clubes en la Selección', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Exportar los Datos"""

df.to_csv('jugadores.csv', index=False)
df.to_json('jugadores.json', orient='records', indent=4)